#!/usr/bin/env python3
"""Generate cppscheme2's Unicode case-mapping + classification tables from the
HOST Python's Unicode database.

Policy (project decision "B3"): the latest Python release's Unicode tables are
THE standard.  pyscheme uses Python's str/char methods directly; this script
dumps the SAME data to C++ so cppscheme2 stays in parity.  Re-run after a Python
Unicode-version bump.  The mappings here are per-codepoint and match Python's
str.upper()/lower()/casefold() and char predicates (isalpha/isdigit/isspace/
isupper/islower) EXACTLY -- except context-sensitive rules (notably Greek final
sigma), which a per-codepoint table cannot express; r7rs-tests is lenient there.

Usage:  python tools/gen_unicode_tables.py [<cppscheme2 src dir>]
Writes <src>/unicode_tables.h and <src>/unicode_tables.cpp.
"""
import sys
import os
import unicodedata

MAX_CP = 0x110000
SUR_LO, SUR_HI = 0xD800, 0xDFFF


def is_surrogate(cp):
    return SUR_LO <= cp <= SUR_HI


def gather_case():
    """Return (upper, lower, fold) lists of (cp, [result codepoints]) for every
    codepoint whose full mapping differs from itself."""
    upper, lower, fold = [], [], []
    for cp in range(MAX_CP):
        if is_surrogate(cp):
            continue
        ch = chr(cp)
        u = ch.upper()
        if u != ch:
            upper.append((cp, [ord(x) for x in u]))
        lo = ch.lower()
        if lo != ch:
            lower.append((cp, [ord(x) for x in lo]))
        f = ch.casefold()
        if f != ch:
            fold.append((cp, [ord(x) for x in f]))
    return upper, lower, fold


def gather_ranges(pred):
    """Compress a per-codepoint predicate into a sorted list of [lo, hi] ranges."""
    ranges = []
    start = None
    for cp in range(MAX_CP):
        on = (not is_surrogate(cp)) and pred(chr(cp))
        if on and start is None:
            start = cp
        elif (not on) and start is not None:
            ranges.append((start, cp - 1))
            start = None
    if start is not None:
        ranges.append((start, MAX_CP - 1))
    return ranges


def emit_case_array(out, name, entries):
    out.append("static const CaseEntry %s[] = {" % name)
    line = "  "
    for cp, res in entries:
        n = len(res)
        padded = (res + [0, 0, 0])[:3]
        cell = "{0x%X,%d,{0x%X,0x%X,0x%X}}," % (cp, n, padded[0], padded[1], padded[2])
        if len(line) + len(cell) > 96:
            out.append(line)
            line = "  "
        line += cell
    if line.strip():
        out.append(line)
    out.append("};")
    out.append("static const int %s_count = %d;" % (name, len(entries)))


def emit_range_array(out, name, ranges):
    out.append("static const Range %s[] = {" % name)
    line = "  "
    for lo, hi in ranges:
        cell = "{0x%X,0x%X}," % (lo, hi)
        if len(line) + len(cell) > 96:
            out.append(line)
            line = "  "
        line += cell
    if line.strip():
        out.append(line)
    out.append("};")
    out.append("static const int %s_count = %d;" % (name, len(ranges)))


def main():
    src = sys.argv[1] if len(sys.argv) > 1 else \
        os.path.join(os.path.dirname(__file__), "..", "..", "4CPPScheme2", "src")
    src = os.path.abspath(src)
    uver = unicodedata.unidata_version
    pyver = "%d.%d.%d" % sys.version_info[:3]

    sys.stderr.write("Gathering case mappings...\n")
    upper, lower, fold = gather_case()
    sys.stderr.write("Gathering classification ranges...\n")
    alpha = gather_ranges(lambda c: c.isalpha())
    digit = gather_ranges(lambda c: c.isdigit())
    space = gather_ranges(lambda c: c.isspace())
    upper_c = gather_ranges(lambda c: c.isupper())
    lower_c = gather_ranges(lambda c: c.islower())

    banner = ("// GENERATED by 3PyScheme/tools/gen_unicode_tables.py -- DO NOT EDIT.\n"
              "// Source: Python %s, Unicode %s.\n" % (pyver, uver))

    # ---- header ----
    h = [banner, "#pragma once", "#include <cstdint>", "",
         "// Unicode case mapping + classification, matching pyscheme's host-Python",
         "// str/char methods (Unicode %s)." % uver,
         "namespace unicode",
         "{",
         "// Full case mapping of cp into out[0..n); returns n (1..3).  Unmapped",
         "// codepoints yield themselves (n==1).  char-level ops use n==1 only.",
         "int upcase(char32_t cp, char32_t out[3]);",
         "int downcase(char32_t cp, char32_t out[3]);",
         "int foldcase(char32_t cp, char32_t out[3]);",
         "bool is_alpha(char32_t cp);   // Python str.isalpha",
         "bool is_digit(char32_t cp);   // Python str.isdigit",
         "bool is_space(char32_t cp);   // Python str.isspace",
         "bool is_upper(char32_t cp);   // Python str.isupper",
         "bool is_lower(char32_t cp);   // Python str.islower",
         "}", ""]
    with open(os.path.join(src, "unicode_tables.h"), "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(h))

    # ---- source ----
    c = [banner, '#include "unicode_tables.h"', "#include <algorithm>", "",
         "namespace {",
         "struct CaseEntry { char32_t cp; uint8_t n; char32_t r[3]; };",
         "struct Range { char32_t lo, hi; };", ""]
    emit_case_array(c, "kUpper", upper)
    emit_case_array(c, "kLower", lower)
    emit_case_array(c, "kFold", fold)
    c.append("")
    emit_range_array(c, "kAlpha", alpha)
    emit_range_array(c, "kDigit", digit)
    emit_range_array(c, "kSpace", space)
    emit_range_array(c, "kUpperC", upper_c)
    emit_range_array(c, "kLowerC", lower_c)
    c.append("")
    c.append("""
int map_case(char32_t cp, const CaseEntry* tab, int n, char32_t out[3])
   {
   int lo = 0, hi = n - 1;
   while (lo <= hi)
      {
      int mid = (lo + hi) / 2;
      if (tab[mid].cp == cp)
         {
         for (int i = 0; i < tab[mid].n; ++i) out[i] = tab[mid].r[i];
         return tab[mid].n;
         }
      if (tab[mid].cp < cp) lo = mid + 1; else hi = mid - 1;
      }
   out[0] = cp;
   return 1;
   }

bool in_ranges(char32_t cp, const Range* tab, int n)
   {
   int lo = 0, hi = n - 1;
   while (lo <= hi)
      {
      int mid = (lo + hi) / 2;
      if (cp < tab[mid].lo) hi = mid - 1;
      else if (cp > tab[mid].hi) lo = mid + 1;
      else return true;
      }
   return false;
   }
}  // namespace

namespace unicode {
int upcase(char32_t cp, char32_t out[3]) { return map_case(cp, kUpper, kUpper_count, out); }
int downcase(char32_t cp, char32_t out[3]) { return map_case(cp, kLower, kLower_count, out); }
int foldcase(char32_t cp, char32_t out[3]) { return map_case(cp, kFold, kFold_count, out); }
bool is_alpha(char32_t cp) { return in_ranges(cp, kAlpha, kAlpha_count); }
bool is_digit(char32_t cp) { return in_ranges(cp, kDigit, kDigit_count); }
bool is_space(char32_t cp) { return in_ranges(cp, kSpace, kSpace_count); }
bool is_upper(char32_t cp) { return in_ranges(cp, kUpperC, kUpperC_count); }
bool is_lower(char32_t cp) { return in_ranges(cp, kLowerC, kLowerC_count); }
}
""")
    with open(os.path.join(src, "unicode_tables.cpp"), "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(c))

    sys.stderr.write(
        "Wrote unicode_tables.{h,cpp} to %s\n  Unicode %s | upper=%d lower=%d fold=%d "
        "| alpha=%d digit=%d space=%d upperC=%d lowerC=%d ranges\n"
        % (src, uver, len(upper), len(lower), len(fold),
           len(alpha), len(digit), len(space), len(upper_c), len(lower_c)))


if __name__ == "__main__":
    main()
